---
- hosts: all

  vars_files:
    - ../config.yml
    # Load instructions for your generator
    - ../openapphack.generateapp.yml
    # Load instructions for your app installer
    - ../openapphack.installapp.yml
    # Load instructions for your app runner
    - ../openapphack.runapp.yml


  pre_tasks:
    - include: tasks/init-debian.yml
      when: ansible_os_family == 'Debian'


  roles:
    # Essential roles.
    - openapphack.firewall
    - openapphack.git
    - openapphack.postfix
    - { role: openapphack.apache, when: openapphackvm_webserver == 'apache' }
    - { role: openapphack.nginx, when: openapphackvm_webserver == 'nginx' }
    - openapphack.mysql

    # Conditionally-installed roles.
    - { role: openapphack.nodejs, when: '"nodejs" in installed_extras' }
    - { role: openapphack.ruby, when: '"ruby" in installed_extras' }

    # Roles for security and stability on production.
    - { role: openapphack.security, when: extra_security_enabled }

  tasks:
    - name: Check if your app is already set up.
      stat: "path={{ app_path }}"
      register: app

    - include: tasks/sshd.yml
    - include: tasks/extras.yml
    - include: tasks/www.yml
      when: ansible_os_family == 'Debian'

    # Generate your App .
    - include: tasks/generate-app.yml
      when: generate_app

      # Install Your App .
    - include: tasks/install-app.yml
      when: install_app

    - include: tasks/cron.yml
      # Run Your App .
    - include: tasks/run-app.yml
      when: run_app
